# Generated by Django 5.1.1 on 2024-09-13 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Poster_Link', models.URLField()),
                ('Series_Title', models.CharField(max_length=70)),
                ('Released_Year', models.ImageField(upload_to='')),
                ('Certificate', models.CharField(max_length=10)),
                ('Runtime', models.CharField(max_length=10)),
                ('Genre', models.CharField(max_length=40)),
                ('IMDB_Rating', models.FloatField()),
                ('Overview', models.TextField()),
                ('Meta_score', models.IntegerField(blank=True, null=True)),
                ('Director', models.CharField(max_length=40)),
                ('Stars', models.CharField(max_length=100)),
                ('Gross', models.BigIntegerField()),
            ],
        ),
    ]
