# Generated by Django 5.1.1 on 2024-09-14 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_moves', '0003_alter_movie_meta_score'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='movie',
            options={'ordering': ['IMDB_Rating']},
        ),
        migrations.AlterField(
            model_name='movie',
            name='Poster_Link',
            field=models.ImageField(upload_to=''),
        ),
    ]
