# Generated by Django 5.1.1 on 2024-09-14 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_moves', '0004_alter_movie_options_alter_movie_poster_link'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='Released_Year',
        ),
        migrations.AlterField(
            model_name='movie',
            name='Poster_Link',
            field=models.URLField(),
        ),
    ]
