# Generated by Django 5.1.1 on 2024-09-14 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_moves', '0005_remove_movie_released_year_alter_movie_poster_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='Released_Year',
            field=models.IntegerField(default=0),
        ),
    ]
